{
 "title": "Flask-app dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "method", "label": "Method", "query": { "query": "label_values(method)" } },
   { "name": "status", "label": "Status", "query": "2,3,4,5" },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[$__range]))\r\n/\r\nsum(rate(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg request duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[$__range])\r\n/\r\nrate(http_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by method",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top endpoints",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum(rate(http_requests_total{exported_endpoint!='/metrics'}[$__range])) by (exported_endpoint)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top endpoints",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum(rate(http_requests_total{exported_endpoint!='/metrics'}[$__range])) by (exported_endpoint)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{method=~\"$method\",status=~\"${status}..\"}[$__range])) by (method,status)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{app=\"flask-app\"} |= `$filter` | json | method =~ `$method` | status =~ `${status}..`"
    }
   ]
  },
  { "title": "k8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not running pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node healthy?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}