name: Build Test
on:
  # push:
  #   branches:
  #     - dev
  #   paths:
  #     - app/**
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - app/**
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:
          - "dev"
          - "prod"
        required: true

permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.env || github.event_name == 'push' && 'dev' || github.event_name == 'pull_request' && 'prod' || null}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build -t ${{ vars.ECR_URI}}:${{ github.sha }} .

      - name: Save image to tar
        run: |
          docker save ${{ vars.ECR_URI}}:${{ github.sha }} -o image.tar

      - name: Compress
        run: |
          gzip image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: app/image.tar.gz

  test:
    needs: build
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.env || github.event_name == 'push' && 'dev' || github.event_name == 'pull_request' && 'prod' || null}}
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Extract
        run: |
          gunzip image.tar.gz

      - name: Load docker image
        run: |
          docker load -i image.tar

      - name: Run docker image
        run: |
          docker run -d --name flask-app -p 5000:5000 ${{ vars.ECR_URI}}:${{ github.sha }}

      - name: Wait for healthcheck
        run: |
          for i in {1..30}; do
            if curl -i -X GET 127.0.0.1:5000/health; then
              echo "Flask-app is healthy"
              exit 0
            fi
            echo "Waiting for flask-app..."
            sleep 2
          done
                    
          echo "Flaks-app failed to start"
          docker logs flask-app
          exit 1

      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: flask-app:latest
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
  deploy:
    if: (github.event_name == 'workflow_dispatch' && inputs.env == 'dev') || github.event_name == 'push'
    needs: test
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Extract
        run: |
          gunzip image.tar.gz

      - name: Load docker image
        run: |
          docker load -i image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_URI }}

      - name: Push to ECR
        run: |
          docker push ${{ vars.ECR_URI}}:${{ github.sha }}

      - name: Update deployment.yaml
        run: |
          sed -i "s|image: .*|image: ${{ vars.ECR_URI}}:${{ github.sha }}|" k8s/deployment.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || exit 0
          git push
